import {segmentTargetWithLexicon,rankDecompositions,validateStrictRebus} from './src/phonetic-engine.js';
import {exportRebusPdf,exportRebusSetPdf,worksheetCopy,normalizeWorksheetSet} from './src/pdf-export.js';
import {buildTherapyActivities,selectTherapyActivity,activityInstruction} from './src/therapy-activities.js';
import {normalizeLayout,moveSessionItem,buildSessionProgression,paginateSession,sessionItemKey} from './src/session-plan.js';
import {auditRebusAssets} from './src/asset-audit.js';
const state={catalog:[],lexicon:[],corpus:[],therapyTargets:[],assetRegistry:{},current:null,score:0,streak:0,lastId:null,creatorCurrent:null,sheetMode:'pro',worksheetSet:[],activityId:''};
const $=s=>document.querySelector(s);const els={age:$('#age'),rebus:$('#rebus'),answer:$('#answer'),form:$('#answerForm'),feedback:$('#feedback'),score:$('#score'),streak:$('#streak'),difficulty:$('#difficulty'),hint:$('#hint'),solution:$('#solution'),newRebus:$('#newRebus'),creatorForm:$('#creatorForm'),target:$('#target'),creatorFeedback:$('#creatorFeedback'),result:$('#result'),resultLabel:$('#resultLabel'),resultWord:$('#resultWord'),sheetInstruction:$('#sheetInstruction'),creatorRebus:$('#creatorRebus'),phoneticProof:$('#phoneticProof'),worksheetAnswer:$('#worksheetAnswer'),changeImage:$('#changeImage'),childMode:$('#childMode'),proMode:$('#proMode'),patientName:$('#patientName'),sessionDate:$('#sessionDate'),worksheetLevel:$('#worksheetLevel'),therapyActivity:$('#therapyActivity'),worksheetLayout:$('#worksheetLayout'),therapyPanel:$('#therapyPanel'),therapyLabel:$('#therapyLabel'),therapyDescription:$('#therapyDescription'),therapyInstruction:$('#therapyInstruction'),assetAuditPanel:$('#assetAuditPanel'),assetAuditSummary:$('#assetAuditSummary'),assetAuditList:$('#assetAuditList'),addToWorksheet:$('#addToWorksheet'),queueCount:$('#queueCount'),worksheetQueue:$('#worksheetQueue'),printRebus:$('#printRebus'),downloadRebus:$('#downloadRebus'),downloadSeries:$('#downloadSeries'),exportFeedback:$('#exportFeedback')};
function normalize(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function setFeedback(text,type=''){if(els.feedback){els.feedback.textContent=text;els.feedback.className='feedback'+(type?' '+type:'')}}function setExportFeedback(text,type=''){if(els.exportFeedback){els.exportFeedback.textContent=text;els.exportFeedback.className='export-feedback'+(type?' '+type:'')}}function readingOf(p){return p.reading||p.label||''}
function pieceNode(piece){const box=document.createElement('div');box.className='piece';const img=document.createElement('img');img.src=piece.image;img.alt=readingOf(piece);const label=document.createElement('span');label.textContent=readingOf(piece);box.append(img,label);return box}
function renderPieces(container,pieces){container.replaceChildren();pieces.forEach((p,i)=>{container.appendChild(pieceNode(p));if(i<pieces.length-1){const plus=document.createElement('span');plus.className='plus';plus.textContent='+';container.appendChild(plus)}})}
function targetEntry(w){return state.corpus.find(item=>normalize(item.target)===w)}function generatedPieces(target){return rankDecompositions(segmentTargetWithLexicon(target.targetIpa,state.lexicon,4))[0]||null}function worksheetMeta(){return {patient:els.patientName?.value.trim()||'',date:els.sessionDate?.value||'',level:els.worksheetLevel?.value||''}}function worksheetLayout(){return normalizeLayout(els.worksheetLayout?.value||1)}
function candidateFromTarget(target){if(!target||target.mode!=='strict'||target.assets!=='ready'||!target.targetIpa)return null;const pieces=generatedPieces(target);if(!pieces)return null;const c={answer:target.target,targetIpa:target.targetIpa,pieces:pieces.map(p=>({...p,reading:p.label})),therapyActivities:buildTherapyActivities(target,state.therapyTargets)};return validateStrictRebus(c).ok?c:null}
function currentActivity(){return selectTherapyActivity(state.creatorCurrent?.therapyActivities||[],state.activityId)}
function renderActivityOptions(){if(!els.therapyActivity||!state.creatorCurrent)return;const activities=state.creatorCurrent.therapyActivities||[];els.therapyActivity.replaceChildren();activities.forEach(activity=>{const option=document.createElement('option');option.value=activity.id;option.textContent=activity.label;els.therapyActivity.appendChild(option)});const selected=selectTherapyActivity(activities,state.activityId);state.activityId=selected?.id||'';if(state.activityId)els.therapyActivity.value=state.activityId;renderActivityPanel()}
function renderActivityPanel(){const activity=currentActivity();if(!els.therapyPanel)return;els.therapyPanel.hidden=!activity;if(!activity)return;els.therapyLabel.textContent=activity.label;els.therapyDescription.textContent=activity.description;els.therapyInstruction.textContent=activityInstruction(activity,state.sheetMode)}
function renderAssetAudit(){if(!els.assetAuditPanel||!state.creatorCurrent)return;const audit=auditRebusAssets(state.creatorCurrent.pieces,state.assetRegistry);els.assetAuditPanel.hidden=state.sheetMode!=='pro';els.assetAuditSummary.textContent=audit.allClinicalApproved?'Toutes les images sont marquées comme validées cliniquement.':audit.allDocumented?'Provenance documentée, mais validation clinique encore incomplète.':'Au moins une image historique a une provenance ou une validation encore à auditer.';els.assetAuditList.replaceChildren();audit.items.forEach(item=>{const row=document.createElement('div');row.className='asset-audit-item';const title=document.createElement('strong');title.textContent=item.label;const status=document.createElement('span');status.textContent=item.statusLabel;const source=document.createElement('small');source.textContent=item.documented?`${item.source}${item.license?` · ${item.license}`:''}`:'Source structurée absente';row.append(title,status,source);els.assetAuditList.appendChild(row)})}
function createRebus(){const wanted=normalize(els.target.value);els.creatorFeedback.className='creator-feedback';setExportFeedback('');if(!wanted){els.result.hidden=true;els.creatorFeedback.textContent='Écris d’abord un mot.';return}const target=targetEntry(wanted);if(!target){els.result.hidden=true;els.creatorFeedback.textContent='Ce mot n’est pas encore dans le corpus pilote.';return}if(target.mode!=='strict'){els.result.hidden=true;els.creatorFeedback.textContent=`Refus phonétique : ${target.reason||'item non strict.'}`;return}if(target.assets!=='ready'){els.result.hidden=true;els.creatorFeedback.textContent='La décomposition est étudiée, mais les images nécessaires ne sont pas encore prêtes.';return}const c=candidateFromTarget(target);if(!c){els.result.hidden=true;els.creatorFeedback.textContent='Aucune décomposition exacte disponible avec les concepts actifs.';return}state.creatorCurrent=c;state.activityId=c.therapyActivities[0]?.id||'';renderCreator()}
function applySheetMode(mode){if(!['child','pro'].includes(mode))return;state.sheetMode=mode;if(!state.creatorCurrent)return;const copy=worksheetCopy(state.creatorCurrent,mode);const activity=currentActivity();els.result.dataset.sheetMode=mode;els.childMode.setAttribute('aria-pressed',String(mode==='child'));els.proMode.setAttribute('aria-pressed',String(mode==='pro'));els.childMode.classList.toggle('secondary',mode!=='child');els.proMode.classList.toggle('secondary',mode!=='pro');els.resultLabel.textContent=mode==='child'?'Enfant':'Pro';els.resultWord.textContent=copy.title;els.sheetInstruction.textContent=activity?activityInstruction(activity,mode):copy.subtitle;els.worksheetAnswer.hidden=!copy.answerLine;els.phoneticProof.textContent=mode==='pro'?copy.proof:'';renderActivityPanel();renderAssetAudit()}
function renderCreator(){els.result.hidden=false;els.creatorFeedback.textContent='Rébus créé.';renderPieces(els.creatorRebus,state.creatorCurrent.pieces);els.changeImage.disabled=true;renderActivityOptions();applySheetMode(state.sheetMode);renderQueue()}
function queueControl(label,title,onClick,disabled=false){const button=document.createElement('button');button.type='button';button.className='queue-mini';button.textContent=label;button.title=title;button.setAttribute('aria-label',title);button.disabled=disabled;button.addEventListener('click',onClick);return button}
function currentSessionKey(){return sessionItemKey({...state.creatorCurrent,activity:currentActivity()})}
function renderQueue(){state.worksheetSet=normalizeWorksheetSet(state.worksheetSet,4);const progression=buildSessionProgression(state.worksheetSet);els.queueCount.textContent=`${state.worksheetSet.length} / 4`;els.downloadSeries.disabled=state.worksheetSet.length<2;els.worksheetQueue.replaceChildren();progression.forEach((step,i)=>{const row=document.createElement('div');row.className='queue-item';const copy=document.createElement('div');copy.className='queue-copy';const strong=document.createElement('strong');strong.textContent=`${step.step}. ${step.target}`;const meta=document.createElement('span');meta.textContent=step.activity||'Activité';copy.append(strong,meta);const controls=document.createElement('div');controls.className='queue-controls';controls.append(queueControl('↑','Monter',()=>{state.worksheetSet=moveSessionItem(state.worksheetSet,i,i-1);renderQueue()},i===0),queueControl('↓','Descendre',()=>{state.worksheetSet=moveSessionItem(state.worksheetSet,i,i+1);renderQueue()},i===state.worksheetSet.length-1),queueControl('×','Retirer',()=>{state.worksheetSet.splice(i,1);renderQueue()}));row.append(copy,controls);els.worksheetQueue.appendChild(row)});if(els.addToWorksheet)els.addToWorksheet.disabled=!state.creatorCurrent||state.worksheetSet.length>=4||state.worksheetSet.some(item=>sessionItemKey(item)===currentSessionKey())}
function addCurrentToQueue(){if(!state.creatorCurrent)return;state.worksheetSet=normalizeWorksheetSet([...state.worksheetSet,{...state.creatorCurrent,activity:currentActivity()}],4);renderQueue();setExportFeedback('Ajouté à la séance.','good')}
async function downloadPdf(){if(!state.creatorCurrent)return;try{els.downloadRebus.disabled=true;setExportFeedback('Création du PDF…');const f=await exportRebusPdf({...state.creatorCurrent,activity:currentActivity()},{mode:state.sheetMode,metadata:worksheetMeta()});setExportFeedback('PDF créé.','good')}catch(e){console.error(e);setExportFeedback('PDF impossible.','bad')}finally{els.downloadRebus.disabled=false}}
async function downloadSeries(){if(state.worksheetSet.length<2)return;try{els.downloadSeries.disabled=true;const layout=worksheetLayout();setExportFeedback('Création du PDF…');await exportRebusSetPdf(state.worksheetSet,{mode:state.sheetMode,metadata:worksheetMeta(),layout});setExportFeedback('PDF de séance créé.','good')}catch(e){console.error(e);setExportFeedback('PDF impossible.','bad')}finally{renderQueue()}}
function isStrictCatalogRebus(r){return validateStrictRebus(r).ok}function eligible(){const age=Number(els.age?.value||7);return state.catalog.filter(r=>r.minAge<=age&&isStrictCatalogRebus(r))}function pickRebus(){if(!els.rebus)return;const pool=eligible();if(!pool.length)return;let choices=pool.filter(r=>r.id!==state.lastId);if(!choices.length)choices=pool;state.current=choices[Math.floor(Math.random()*choices.length)];state.lastId=state.current.id;renderGame()}function renderGame(){const r=state.current;renderPieces(els.rebus,r.pieces);els.answer.value='';els.difficulty.textContent=`Niveau ${r.difficulty}`;setFeedback('')}function validate(){const typed=normalize(els.answer.value);if(typed===normalize(state.current.answer)){state.score+=10*state.current.difficulty;state.streak+=1;els.score.textContent=state.score;els.streak.textContent=`🔥 ${state.streak}`;setFeedback('Bravo !','good');setTimeout(pickRebus,1100)}else{state.streak=0;els.streak.textContent='🔥 0';setFeedback('Essaie encore.','bad')}}
async function loadJSON(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(path);return r.json()}async function init(){try{const [catalog,lexicon,corpus,therapy,assets]=await Promise.all([loadJSON('data/rebus.json'),loadJSON('data/lexicon-seed.json'),loadJSON('data/corpus-pilot.json'),loadJSON('data/therapy-targets.json'),loadJSON('data/asset-sources.json')]);state.catalog=catalog;state.lexicon=lexicon;state.corpus=corpus.items||[];state.therapyTargets=therapy.targets||[];state.assetRegistry=assets||{};createRebus();pickRebus()}catch(e){els.result.hidden=true;els.creatorFeedback.textContent='Chargement impossible.'}}
els.creatorForm?.addEventListener('submit',e=>{e.preventDefault();createRebus()});els.childMode?.addEventListener('click',()=>applySheetMode('child'));els.proMode?.addEventListener('click',()=>applySheetMode('pro'));els.therapyActivity?.addEventListener('change',()=>{state.activityId=els.therapyActivity.value;applySheetMode(state.sheetMode);renderQueue()});els.addToWorksheet?.addEventListener('click',addCurrentToQueue);els.printRebus?.addEventListener('click',()=>window.print());els.downloadRebus?.addEventListener('click',downloadPdf);els.downloadSeries?.addEventListener('click',downloadSeries);els.form?.addEventListener('submit',e=>{e.preventDefault();validate()});els.hint?.addEventListener('click',()=>state.current&&setFeedback(`💡 ${state.current.hint}`));els.solution?.addEventListener('click',()=>state.current&&setFeedback(`Réponse : ${state.current.answer}.`));els.newRebus?.addEventListener('click',pickRebus);els.age?.addEventListener('change',pickRebus);init();
