const state={catalog:[],current:null,score:0,streak:0,lastId:null};
const els={age:document.querySelector('#age'),rebus:document.querySelector('#rebus'),answer:document.querySelector('#answer'),form:document.querySelector('#answerForm'),feedback:document.querySelector('#feedback'),score:document.querySelector('#score'),streak:document.querySelector('#streak'),difficulty:document.querySelector('#difficulty'),hint:document.querySelector('#hint'),solution:document.querySelector('#solution'),newRebus:document.querySelector('#newRebus')};
function normalize(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function setFeedback(text,type=''){els.feedback.textContent=text;els.feedback.className='feedback'+(type?' '+type:'')}
function eligible(){const age=Number(els.age.value);return state.catalog.filter(r=>r.minAge<=age)}
function pickRebus(){const pool=eligible();if(!pool.length){setFeedback('Aucun rébus disponible pour cet âge.','bad');return}let choices=pool.filter(r=>r.id!==state.lastId);if(!choices.length)choices=pool;state.current=choices[Math.floor(Math.random()*choices.length)];state.lastId=state.current.id;render()}
function render(){const r=state.current;els.rebus.replaceChildren();r.pieces.forEach((piece,index)=>{const box=document.createElement('div');box.className='piece';const img=document.createElement('img');img.src=piece.image;img.alt=piece.reading;box.appendChild(img);els.rebus.appendChild(box);if(index<r.pieces.length-1){const plus=document.createElement('span');plus.className='plus';plus.textContent='+';plus.setAttribute('aria-hidden','true');els.rebus.appendChild(plus)}});els.answer.value='';els.difficulty.textContent=`Niveau ${r.difficulty}`;setFeedback('Les images donnent des sons français.');els.answer.focus()}
function validate(){const typed=normalize(els.answer.value);if(!typed){setFeedback('Écris d’abord une réponse.','bad');return}if(typed===normalize(state.current.answer)){state.score+=10*state.current.difficulty;state.streak+=1;els.score.textContent=state.score;els.streak.textContent=`🔥 ${state.streak}`;setFeedback(`Bravo ! ${state.current.answer} — ${state.current.pieces.map(p=>p.reading).join(' + ')}.`,'good');setTimeout(pickRebus,1100)}else{state.streak=0;els.streak.textContent='🔥 0';setFeedback('Ce n’est pas encore le bon son. Prononce chaque image à voix haute.','bad')}}
async function init(){try{const response=await fetch('data/rebus.json',{cache:'no-store'});if(!response.ok)throw new Error('catalog');state.catalog=await response.json();pickRebus()}catch(error){setFeedback('Le catalogue ne peut pas être chargé. Lance Rebulo via un serveur HTTP ou GitHub Pages.','bad')}}
els.form.addEventListener('submit',e=>{e.preventDefault();validate()});
els.hint.addEventListener('click',()=>{if(state.current)setFeedback(`💡 ${state.current.hint}`)});
els.solution.addEventListener('click',()=>{if(!state.current)return;state.streak=0;els.streak.textContent='🔥 0';setFeedback(`Solution : ${state.current.answer}. Sons : ${state.current.pieces.map(p=>`${p.reading} ${p.ipa}`).join(' + ')}.`)});
els.newRebus.addEventListener('click',pickRebus);
els.age.addEventListener('change',()=>{state.streak=0;els.streak.textContent='🔥 0';pickRebus()});
init();
