import {createNamingSession,recordNamingObservation,namingSessionExport} from './src/naming-test-session.js';

const $=selector=>document.querySelector(selector);
const els={setup:$('#setupPanel'),trial:$('#trialPanel'),complete:$('#completePanel'),concept:$('#conceptSelect'),sessionCode:$('#sessionCode'),start:$('#startSession'),progress:$('#trialProgress'),badge:$('#conceptBadge'),image:$('#stimulusImage'),form:$('#responseForm'),submit:$('#responseForm button[type="submit"]'),response:$('#responseVerbatim'),hesitation:$('#hesitation'),noResponse:$('#noResponse'),summary:$('#completeSummary'),exportJson:$('#exportJson'),newSession:$('#newSession'),status:$('#status')};
let comparisons=[];let activeComparison=null;let activeSession=null;let ordered=[];let index=0;let stimulusReady=false;

function setStatus(text=''){els.status.textContent=text;}
function orderMode(){return document.querySelector('input[name="orderMode"]:checked')?.value||'random';}
function candidateById(id){return activeComparison?.candidates.find(item=>item.candidateId===id)||null;}
function setTrialEnabled(enabled){stimulusReady=enabled;els.submit.disabled=!enabled;els.response.disabled=!enabled||els.noResponse.checked;els.hesitation.disabled=!enabled;els.noResponse.disabled=!enabled;els.form.setAttribute('aria-busy',String(!enabled));}
function renderTrial(){const candidate=candidateById(activeSession.candidateIds[index]);if(!candidate)return finish();els.progress.textContent=`Prototype ${index+1} / ${activeSession.candidateIds.length}`;els.badge.textContent='Prototype visuel';els.response.value='';els.hesitation.checked=false;els.noResponse.checked=false;setTrialEnabled(false);setStatus('Chargement du stimulus…');els.image.alt='Prototype visuel à dénommer';els.image.onload=()=>{setTrialEnabled(true);setStatus('');els.response.focus();};els.image.onerror=()=>{setTrialEnabled(false);els.image.alt='Stimulus indisponible';setStatus('Stimulus indisponible. N’enregistre aucune réponse pour cette passation.');};els.image.src=candidate.asset;}
function start(){activeComparison=comparisons.find(item=>item.concept===els.concept.value)||null;activeSession=createNamingSession(activeComparison,{sessionCode:els.sessionCode.value,orderMode:orderMode()});if(!activeSession){setStatus('Ajoute un code de session anonyme.');return}ordered=activeSession.candidateIds.map(candidateById).filter(Boolean);index=0;els.setup.hidden=true;els.complete.hidden=true;els.trial.hidden=false;setStatus('');renderTrial();}
function finish(){stimulusReady=false;els.trial.hidden=true;els.complete.hidden=false;els.summary.textContent=`${activeSession.observations.length} réponse(s) enregistrée(s) pour « ${activeSession.concept} » — révision ${activeSession.comparisonRevision}.`;}
function downloadJson(){const payload=namingSessionExport(activeSession);if(!payload)return;const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`rebulo-naming-${payload.concept}-${payload.comparisonRevision}-${payload.sessionCode}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setStatus('Export JSON créé localement.');}
function reset(){activeComparison=null;activeSession=null;ordered=[];index=0;stimulusReady=false;els.complete.hidden=true;els.trial.hidden=true;els.setup.hidden=false;els.sessionCode.value='';setStatus('');els.sessionCode.focus();}

els.noResponse?.addEventListener('change',()=>{if(!stimulusReady)return;els.response.disabled=els.noResponse.checked;if(els.noResponse.checked)els.response.value='';});
els.form?.addEventListener('submit',event=>{event.preventDefault();if(!stimulusReady){setStatus('Le stimulus doit être visible avant d’enregistrer une réponse.');return}const candidate=ordered[index];const updated=recordNamingObservation(activeSession,candidate,{responseVerbatim:els.response.value,hesitation:els.hesitation.checked,noResponse:els.noResponse.checked});if(!updated){setStatus('Note la première réponse, ou coche « Pas de réponse ».');return}activeSession=updated;index+=1;setStatus('');if(index>=ordered.length)finish();else renderTrial();});
els.start?.addEventListener('click',start);els.exportJson?.addEventListener('click',downloadJson);els.newSession?.addEventListener('click',reset);

async function init(){try{const response=await fetch('./data/pictogram-prototype-comparisons.json',{cache:'no-store'});if(!response.ok)throw new Error('comparisons unavailable');const registry=await response.json();comparisons=(registry.comparisons||[]).filter(item=>item.activationState==='inactive_until_human_decision'&&item.candidates?.length);els.concept.replaceChildren(...comparisons.map(item=>{const option=document.createElement('option');option.value=item.concept;option.textContent=item.concept;return option}));if(!comparisons.length){els.start.disabled=true;setStatus('Aucune comparaison de prototype disponible.');}}catch(error){console.error(error);els.start.disabled=true;setStatus('Impossible de charger les prototypes.');}}
init();
