import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const play=fs.readFileSync(new URL('../src/play-mode.js',import.meta.url),'utf8');
const age=fs.readFileSync(new URL('../src/age-profile.js',import.meta.url),'utf8');
assert.match(html,/Quel âge as-tu \?/);
for(const value of ['5','7','9','12'])assert.match(html,new RegExp(`data-rebulo-age="${value}"`));
assert.match(age,/profileFromAge/,'age must recommend a difficulty profile');
assert.match(age,/dataset\.ageReady='true'/,'age must not block the product on first visit');
assert.doesNotMatch(play,/minAge/,'play selection must not be driven only by age');
assert.match(play,/difficultyProfile/,'play mode must use an explicit difficulty profile');
assert.match(play,/resetCreatorSurface/,'switching back to create must clear stale content');
console.log('age recommendation experience: ok');
