import assert from 'node:assert/strict';
import {resolveFrenchSoundQuery,normalizeFrenchSoundQuery} from '../src/french-sound-search.js';
assert.equal(normalizeFrenchSoundQuery('  RA '),'ra');
assert.deepEqual(resolveFrenchSoundQuery('ra').ipaCandidates,['ʁa']);
assert.deepEqual(resolveFrenchSoundQuery('cha').ipaCandidates,['ʃa']);
assert.deepEqual(resolveFrenchSoundQuery('ou').ipaCandidates,['u']);
assert.deepEqual(resolveFrenchSoundQuery('on').ipaCandidates,['ɔ̃']);
assert.deepEqual(resolveFrenchSoundQuery('ain').ipaCandidates,['ɛ̃']);
assert.deepEqual(resolveFrenchSoundQuery('och').ipaCandidates,['ɔʃ','oʃ']);
assert.equal(resolveFrenchSoundQuery('och').ambiguous,true);
assert.deepEqual(resolveFrenchSoundQuery('ouche').ipaCandidates,['uʃ']);
assert.deepEqual(resolveFrenchSoundQuery('ri').ipaCandidates,['ʁi']);
assert.deepEqual(resolveFrenchSoundQuery('ron').ipaCandidates,['ʁɔ̃']);
assert.deepEqual(resolveFrenchSoundQuery('chon').ipaCandidates,['ʃɔ̃']);
assert.deepEqual(resolveFrenchSoundQuery('jou').ipaCandidates,['ʒu']);
assert.deepEqual(resolveFrenchSoundQuery('oin').ipaCandidates,['wɛ̃']);
assert.deepEqual(resolveFrenchSoundQuery('gn').ipaCandidates,['ɲ']);
assert.deepEqual(resolveFrenchSoundQuery('ph').ipaCandidates,['f']);
assert.deepEqual(resolveFrenchSoundQuery('eu').ipaCandidates,['ø','œ']);
assert.equal(resolveFrenchSoundQuery('eu').ambiguous,true);
assert.deepEqual(resolveFrenchSoundQuery('o').ipaCandidates,['o','ɔ']);
assert.deepEqual(resolveFrenchSoundQuery('xyz').ipaCandidates,[]);
console.log('plain French sound search: ok');
