import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateHardSegmentStrategies,hardSegmentStrategySummary,attachHardSegmentStrategies} from '../src/hard-segment-strategies.js';
const registry=JSON.parse(fs.readFileSync('data/hard-segment-strategies.json','utf8'));
const validation=validateHardSegmentStrategies(registry);assert.equal(validation.valid,true,validation.errors.join('\n'));
const summary=hardSegmentStrategySummary(registry);assert.equal(summary.segmentCount,8);assert.equal(summary.scene,2);assert.ok(summary.alternate>=6);assert.ok(summary.visibleFallbackResearch>=6);assert.equal(summary.composedFallbackResearch,4);
const byIpa=new Map(registry.segments.map(x=>[x.ipa,x]));
assert.equal(byIpa.get('mɑ̃').strategy,'alternate_segmentation_first');
assert.equal(byIpa.get('ɛ̃').fallbackStatus,'contextual_grapheme_rule_not_yet_authorized');
assert.equal(byIpa.get('œʁ').strategy,'scene_comparison');
assert.equal(byIpa.get('tʁ').strategy,'alternate_segmentation_required');
assert.equal(byIpa.get('sjɔ̃').lexicalAssessment.includes('very_high'),true);
const eur=byIpa.get('œʁ'),ar=byIpa.get('aʁ'),al=byIpa.get('al'),di=byIpa.get('di');
assert.ok(ar.visibleFallbackResearch.some(x=>x.label==='R'&&x.ipa==='ʁ'&&x.operationType==='grapheme_sound'));
assert.ok(al.visibleFallbackResearch.some(x=>x.label==='L'&&x.ipa==='l'&&x.operationType==='grapheme_sound'));
assert.ok(al.visibleFallbackResearch.some(x=>x.label==='N'&&x.ipa==='n'&&x.operationType==='grapheme_sound'));
assert.ok(di.visibleFallbackResearch.some(x=>x.label==='D'&&x.ipa==='d'&&x.operationType==='grapheme_sound'));
assert.deepEqual(di.composedFallbackResearch.map(x=>x.ipa).sort(),['dite','mid']);
assert.equal(al.composedFallbackResearch[0].ipa,'ɲal');
assert.equal(eur.composedFallbackResearch[0].ipa,'jœʁ');
assert.ok(di.rejectedFallbacks.some(x=>x.label==='D'&&x.reason.includes('/de/')),'D letter-name must stay rejected for /di/ because its French letter name is /de/');
const attached=attachHardSegmentStrategies([{ipa:'tʁ',usefulUnlocked:29},{ipa:'wa',usefulUnlocked:4}],registry);assert.equal(attached[0].hardSegmentStrategy.strategy,'alternate_segmentation_required');assert.equal('hardSegmentStrategy' in attached[1],false);
const bad=structuredClone(registry);bad.segments.find(x=>x.ipa==='di').rejectedFallbacks=[];assert.equal(validateHardSegmentStrategies(bad).valid,false);
const leaked=structuredClone(registry);leaked.segments.find(x=>x.ipa==='di').visibleFallbackResearch[0].ipa='di';assert.equal(validateHardSegmentStrategies(leaked).valid,true,'registry validation permits declared IPA values; route classification is responsible for exact matching');
const malformed=structuredClone(registry);malformed.segments.find(x=>x.ipa==='di').visibleFallbackResearch[0].operationType='grapheme';assert.equal(validateHardSegmentStrategies(malformed).valid,false);
const wrongComposition=structuredClone(registry);wrongComposition.segments.find(x=>x.ipa==='di').composedFallbackResearch.find(x=>x.ipa==='dite').operations[2].ipa='tə';assert.equal(validateHardSegmentStrategies(wrongComposition).valid,false,'composed fallback must reconstruct its declared IPA exactly');
const activatedComposition=structuredClone(registry);activatedComposition.segments.find(x=>x.ipa==='di').composedFallbackResearch[0].status='authorized';assert.equal(validateHardSegmentStrategies(activatedComposition).valid,false,'composed fallbacks must stay research-only');
console.log('Hard segment strategies: final residual groups have exact research-only compositions without weakening letter-name or strict rules.');
