import assert from 'node:assert/strict';
import fs from 'node:fs';

const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const playCss=fs.readFileSync(new URL('../play-mode.css',import.meta.url),'utf8');
const phraseCss=fs.readFileSync(new URL('../phrase-mode.css',import.meta.url),'utf8');
const mobileCss=fs.readFileSync(new URL('../mobile-layout.css',import.meta.url),'utf8');
const shellState=fs.readFileSync(new URL('../src/create-shell-state.js',import.meta.url),'utf8');
const bootstrap=fs.readFileSync(new URL('../src/app-bootstrap.js',import.meta.url),'utf8');
const creatorKind=fs.readFileSync(new URL('../src/creator-kind.js',import.meta.url),'utf8');
const phraseMode=fs.readFileSync(new URL('../src/phrase-mode.js',import.meta.url),'utf8');

assert.match(html,/id="playArena"[^>]*\shidden\b/,'play arena must start hidden');
assert.match(html,/id="result"[^>]*\shidden\b/,'creator result must start hidden');
assert.match(html,/id="target"[^>]*placeholder="Ex\. merci, cinéma…"/,'creator must start with an example placeholder');
assert.doesNotMatch(html,/id="target"[^>]*\svalue=/,'creator must not fabricate a result on first load');
assert.match(html,/data-creator-ready="false"/,'professional tools must start gated');
assert.equal((html.match(/<button[^>]*data-creator-kind="word"/g)||[]).length,1,'Creator must contain a single static Mot control');
assert.equal((html.match(/<button[^>]*data-creator-kind="phrase"/g)||[]).length,1,'Creator must contain a single static Phrase control');
assert.match(creatorKind,/document\.querySelectorAll\('\[data-creator-kind\]'\)/,'Creator kind controller must reuse existing controls');
assert.match(creatorKind,/if\(existing\.length\)/,'Creator kind controller must not inject a duplicate switch when controls already exist');
assert.match(playCss,/\[hidden\]\{display:none!important\}/,'author CSS must never override the hidden attribute');
assert.match(playCss,/data-creator-ready="false"[^}]*\.session-dock/,'session tools must stay hidden before a creator result exists');
assert.match(mobileCss,/\.creator-row\{grid-template-columns:1fr 1fr/,'mobile creator actions must use a stable two-column action row');
assert.match(mobileCss,/\.creator-row input\{grid-column:1\/-1\}/,'mobile creator input must occupy its own row');
assert.match(mobileCss,/keyboard-open[^}]*#playArena\.play-arena\{[^}]*overflow-y:auto!important/,'keyboard-open play must stay scrollable inside the visible phone viewport');
assert.match(mobileCss,/keyboard-open[^}]*#playAnswerForm\{[^}]*position:sticky[^}]*bottom:0/,'the play answer field must stay reachable immediately above the mobile keyboard');
assert.match(phraseCss,/\.phrase-rebus-token[^}]*max-width:100%[^}]*overflow-x:auto/,'long rebus groups must scroll inside their own width instead of overlapping');
assert.match(phraseCss,/@media\(max-width:520px\)[\s\S]*\.phrase-continuous-flow[^}]*flex-wrap:wrap[^}]*overflow-x:hidden/,'continuous phrase pieces must wrap inside the phone viewport instead of being pushed off-screen');
assert.match(phraseMode,/Pièces du rébus/,'partial phrase UI must label represented pieces');
assert.match(phraseMode,/Texte \/ sons non représentés/,'partial phrase UI must label uncovered text separately');
assert.match(phraseMode,/proof\.dataset\.debugDetails/,'technical phrase diagnostics must remain available without dominating the child-facing copy');
assert.match(shellState,/MutationObserver/,'creator-ready state must follow result visibility changes');
assert.match(shellState,/Écris un mot pour créer un rébus\./,'initial shell cleanup must stay aligned with the canonical empty creator status');
assert.doesNotMatch(shellState,/Écris d’abord un mot\./,'initial shell cleanup must not depend on the retired creator prompt');
assert.match(bootstrap,/id='syllablePosition'/,'syllable identification must expose a dedicated position selector');
assert.match(bootstrap,/finalOption\.hidden=true/,'final syllable must not appear as a duplicate activity option');
assert.match(bootstrap,/activitySelect\.dispatchEvent\(new Event\('change'/,'position changes must reuse the canonical activity change path');
assert.match(bootstrap,/activitySelect\.value=initialId/,'the visible activity selector must stay on the single syllable-identification family entry');

console.log('mobile UX regression guards: one Creator switch, readable partial phrases, viewport-safe phone layout.');
