import assert from 'node:assert/strict';
import {sanitizeFilePart,worksheetCopy,worksheetMetadata,normalizeWorksheetSet,worksheetActivity} from '../src/pdf-export.js';
const rebus={answer:'cinéma',targetIpa:'/sinema/',pieces:[{label:'scie',ipa:'/si/'},{label:'nez',ipa:'/ne/'},{label:'mât',ipa:'/ma/'}]};
assert.equal(sanitizeFilePart('Cinéma !'),'cinema');
const child=worksheetCopy(rebus,'child');assert.equal(child.showAnswer,false);assert.equal(child.showLabels,false);assert.equal(child.showIpa,false);assert.equal(child.answerLine,true);
const pro=worksheetCopy(rebus,'pro');assert.equal(pro.showAnswer,true);assert.equal(pro.showLabels,true);assert.equal(pro.showIpa,true);assert.equal(pro.proof,'/si/ + /ne/ + /ma/ = /sinema/');
assert.deepEqual(worksheetMetadata({patient:'Léa',date:'2026-09-01',level:'Entraînement'}),['Patient / élève : Léa','Date : 2026-09-01','Niveau : Entraînement']);
assert.deepEqual(worksheetMetadata({}),[]);
const activity={label:'Fusion syllabique',childInstruction:'Consigne enfant',proInstruction:'Consigne pro'};
assert.deepEqual(worksheetActivity(activity,'child'),{label:'Fusion syllabique',instruction:'Consigne enfant'});
assert.deepEqual(worksheetActivity(activity,'pro'),{label:'Fusion syllabique',instruction:'Consigne pro'});
assert.equal(worksheetActivity(null,'pro'),null);
const cinemaFusion={...rebus,activity:{id:'syllable-blending',label:'Fusion syllabique'}};
const cinemaWritten={...rebus,activity:{id:'oral-to-written',label:'Du son vers l’écrit'}};
const set=normalizeWorksheetSet([cinemaFusion,cinemaFusion,cinemaWritten,{answer:'merci',pieces:[{label:'mer',ipa:'/mɛʁ/'}],activity:{id:'syllable-blending'}},{answer:'parasol',pieces:[{label:'pas',ipa:'/pa/'}],activity:{id:'syllable-blending'}},{answer:'extra',pieces:[{label:'x',ipa:'/x/'}],activity:{id:'syllable-blending'}}]);
assert.deepEqual(set.map(x=>[x.answer,x.activity?.id]),[['cinéma','syllable-blending'],['cinéma','oral-to-written'],['merci','syllable-blending'],['parasol','syllable-blending']]);
console.log('Rebulo PDF worksheet modes, activities and series: all tests passed.');
