import fs from 'node:fs';import assert from 'node:assert/strict';
const html=fs.readFileSync('phonology-atlas.html','utf8');
const css=fs.readFileSync('phonology-atlas.css','utf8');
const js=fs.readFileSync('src/phonology-atlas-page.js','utf8');
const [screenCss,printCss='']=css.split('@media print');
assert.match(html,/Atlas sons → mots-images → rébus/);
assert.match(html,/Son entendu/);
assert.match(html,/soundSearchForm/);assert.match(html,/Chercher ce son/);
assert.match(html,/ra/);assert.match(html,/och/);assert.match(html,/comme tu l’entends/);
assert.doesNotMatch(html,/Son \/ IPA/);
assert.match(html,/Détails phonétiques/);
assert.match(html,/Seulement les pièces strictes/);
assert.match(html,/bloc sonore entier/);
assert.match(html,/dessins restent en couleur à l’écran/);
assert.match(html,/Mots strictement constructibles dans le lexique actuel/);
assert.match(html,/Preuve d’utilité/);
assert.match(html,/dépend du corpus de référence/);
assert.match(html,/Imprimer \/ enregistrer en PDF/);
assert.match(css,/\.sound-search/);assert.match(css,/@page\{size:A4 portrait/);
assert.doesNotMatch(screenCss,/filter:grayscale\(1\)/);
assert.match(printCss,/\.atlas-card img\{[^}]*filter:grayscale\(1\)/);
assert.match(js,/resolveFrenchSoundQuery/);
assert.match(js,/soundSearchForm/);assert.match(js,/submittedSoundQuery/);assert.match(js,/submitSoundSearch/);
assert.match(js,/soundInput/);
assert.match(js,/filterAtlas/);
assert.match(js,/filterLexicalEntries/);
assert.match(js,/coverage-report\.json/);
assert.match(js,/phonetic-productivity-report\.json/);
assert.match(js,/strict_productive/);
assert.match(js,/Utilisée dans/);
assert.match(js,/Candidate stricte/);
assert.match(js,/preuve d’usage non chargée/);
assert.match(js,/print-copy/);
assert.match(js,/Ce panneau ne représente pas tout le français/);
assert.doesNotMatch(html,/clinical_approved/i);
console.log('phonology atlas page: explicit sound search ok');
