import fs from 'node:fs';import assert from 'node:assert/strict';
const html=fs.readFileSync('phonology-atlas.html','utf8');
const css=fs.readFileSync('phonology-atlas.css','utf8');
const js=fs.readFileSync('src/phonology-atlas-page.js','utf8');
const [screenCss,printCss='']=css.split('@media print');
assert.match(html,/Atlas sons → mots-images → rébus/);
assert.match(html,/Position/);
assert.match(html,/Seulement les pièces strictes/);
assert.match(html,/bloc sonore entier/);
assert.match(html,/dessins restent en couleur à l’écran/);
assert.match(html,/Mots strictement constructibles dans le lexique actuel/);
assert.match(html,/Imprimer \/ enregistrer en PDF/);
assert.match(css,/@page\{size:A4 portrait/);
assert.doesNotMatch(screenCss,/filter:grayscale\(1\)/);
assert.match(printCss,/\.atlas-card img\{[^}]*filter:grayscale\(1\)/);
assert.match(css,/\.lexical-panel/);
assert.match(js,/filterAtlas/);
assert.match(js,/filterLexicalEntries/);
assert.match(js,/coverage-report\.json/);
assert.match(js,/phonemeInput/);
assert.match(js,/print-copy/);
assert.match(js,/Ce panneau ne représente pas tout le français/);
assert.doesNotMatch(html,/clinical_approved/i);
console.log('phonology atlas page: ok');
