import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildProductiveBank} from '../src/rebus-productive-bank.js';
import {normalizeIPA} from '../src/phonetic-engine.js';

const read=path=>JSON.parse(fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8'));
const fragmentIdeas=read('data/rebus-fragment-representation-ideas.json');
const wave1=read('data/rebus-productive-bank-wave1.json');
const wave2=read('data/rebus-productive-bank-wave2.json');
const audit=read('data/rebus-representation-bank-audit.json');
const bank=buildProductiveBank({fragmentIdeas,productiveWaves:[wave1,wave2]});
const usefulIpas=new Set((audit.usefulRows||[]).map(row=>normalizeIPA(row.ipa)).filter(Boolean));
assert.equal(usefulIpas.size,5741);
const seriousSound=sound=>sound.visibleConventions.length>0||sound.representations.some(rep=>rep.editorialStatus==='retain'&&(rep.visualBrief||rep.representationProposed));
const seriousAll=[...bank.values()].filter(seriousSound);
const seriousUseful=seriousAll.filter(sound=>usefulIpas.has(sound.ipa));
const percent=Number((seriousUseful.length/usefulIpas.size*100).toFixed(2));
assert.ok(seriousUseful.length>0);
assert.ok(seriousUseful.length<=seriousAll.length);
console.log(JSON.stringify({usefulSoundDenominator:usefulIpas.size,seriousRepresentationSoundCountAll:seriousAll.length,seriousUsefulSoundCount:seriousUseful.length,usefulSoundSeriousRepresentationPercent:percent},null,2));
