import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildProductiveBank,productiveWaveStats} from '../src/rebus-productive-bank.js';
import {normalizeIPA} from '../src/phonetic-engine.js';
const read=p=>JSON.parse(fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8'));
const fragmentIdeas=read('data/rebus-fragment-representation-ideas.json');
const wave1=read('data/rebus-productive-bank-wave1.json');
const wave2=read('data/rebus-productive-bank-wave2.json');
const wave3=read('data/rebus-productive-bank-wave3.json');
const impacts=read('data/rebus-productive-bank-wave3-impact-ranking.json');
const benches=read('data/rebus-productive-bank-wave3-benchmarks.json');
const metrics=read('data/rebus-productive-bank-wave3-useful-metrics.json');
const stats=productiveWaveStats(wave3);
assert.equal(stats.examinedSoundCount,400);
assert.equal(stats.runtimeActivationCount,0);
assert.ok(stats.totalDistinctExactWordCount>=400);
assert.ok(stats.pictographicProposalCount>=20);
assert.equal(stats.visualBriefCount,stats.pictographicProposalCount);
assert.ok(stats.rejectedCandidateCount>0);
assert.ok(stats.deferredCandidateCount>0);
assert.equal(wave3.representationDefaults.spontaneousNamingRisk,'unknown');
assert.equal(wave3.representationDefaults.humanNamingEvidence,'none');
assert.equal(wave3.representationDefaults.clinicalEvidence,'none');
assert.equal(wave3.representationDefaults.runtimeStatus,'inactive_editorial');
const schemas=[wave1,wave2,wave3].map(w=>w.soundRowSchema||[]);
const sets=[wave1,wave2,wave3].map((w,i)=>new Set((w.soundRows||[]).map(r=>normalizeIPA(r[schemas[i].indexOf('ipa')]))));
assert.equal(sets[2].size,400);
for(const ipa of sets[2])assert.ok(!sets[0].has(ipa)&&!sets[1].has(ipa),`wave3 re-counted ${ipa}`);
assert.ok(impacts.rows.length>=400);
assert.ok(impacts.rows.some(r=>r.marginalUnits>0),'ranking must actually measure historical gaps');
assert.ok(new Set((wave3.soundRows||[]).map(r=>r[wave3.soundRowSchema.indexOf('selectionLane')])).has('A_raw_productive'));
assert.ok(new Set((wave3.soundRows||[]).map(r=>r[wave3.soundRowSchema.indexOf('selectionLane')])).has('B_long_clear_block'));
assert.equal(benches.historical.after.rows.length,20);
assert.equal(benches.control.after.rows.length,20);
assert.ok(benches.historical.after.summary.meanCoverageRatio>=benches.historical.before.summary.meanCoverageRatio);
assert.ok(benches.control.after.summary.meanCoverageRatio>=benches.control.before.summary.meanCoverageRatio-0.0001);
assert.equal(metrics.usefulExactSoundDenominator,5741);
assert.ok(metrics.seriousUsefulExactSoundCount>=215);
assert.ok(metrics.usefulExactSoundSeriousRepresentationPercent>=3.74);
const bank=buildProductiveBank({fragmentIdeas,productiveWaves:[wave1,wave2,wave3]});
for(const raw of wave3.soundRows||[]){const row=Object.fromEntries(wave3.soundRowSchema.map((k,i)=>[k,raw[i]]));const sound=bank.get(normalizeIPA(row.ipa));assert.ok(sound);for(const word of row.exactWords||[]){assert.ok(sound.exactWords.includes(word));const rel=sound.representations.find(r=>r.word===word&&r.source==='Lexique 4');assert.ok(rel);assert.equal(rel.matchStatus,'exact');assert.equal(rel.spontaneousNamingRisk,'unknown');assert.equal(rel.humanNamingEvidence,'none');assert.equal(rel.clinicalEvidence,'none');assert.equal(rel.runtimeStatus,'inactive_editorial');}}
console.log(JSON.stringify({wave:stats,metrics,historical:benches.historical,control:benches.control},null,2));
