import assert from 'node:assert/strict';
import {sourceSyllables,ageBandCandidateForEntry,rebuloUtilityTierForEntry,buildTargetVocabulary,buildSyllableInventory,targetVocabularyStats} from '../src/target-vocabulary.js';
assert.deepEqual(sourceSyllables('mɛʁ.si'),['mɛʁ','si']);assert.deepEqual(sourceSyllables('/si.ne.ma/'),['si','ne','ma']);assert.deepEqual(sourceSyllables(''),[]);
assert.equal(ageBandCandidateForEntry({word:'chat',lemma:'chat',ipa:'ʃa',frequency:120,syllableCount:1,pos:'NOM'}),5);
assert.equal(ageBandCandidateForEntry({word:'cinéma',lemma:'cinéma',ipa:'sinema',frequency:42.1,syllableCount:3,pos:'NOM'}),7);
assert.equal(ageBandCandidateForEntry({word:'extraordinaire',lemma:'extraordinaire',ipa:'ɛkstʁaɔʁdinɛʁ',frequency:12,syllableCount:5,pos:'ADJ'}),12);
assert.equal(ageBandCandidateForEntry({word:'le',lemma:'le',ipa:'lə',frequency:10000,syllableCount:1,pos:'ART:def'}),null);
assert.equal(ageBandCandidateForEntry({word:'rare',lemma:'rare',ipa:'ʁaʁ',frequency:0.1,syllableCount:1,pos:'ADJ'}),null);
assert.equal(rebuloUtilityTierForEntry({word:'chat',lemma:'chat',ipa:'ʃa',frequency:120,syllableCount:1,pos:'NOM'}),'very_common_simple');
assert.equal(rebuloUtilityTierForEntry({word:'cinéma',lemma:'cinéma',ipa:'sinema',frequency:42.1,syllableCount:3,pos:'NOM'}),'child_common');
assert.equal(rebuloUtilityTierForEntry({word:'extraordinaire',lemma:'extraordinaire',ipa:'ɛkstʁaɔʁdinɛʁ',frequency:12,syllableCount:5,pos:'ADJ'}),'teen_adult_common');
assert.equal(rebuloUtilityTierForEntry({word:'astral',lemma:'astral',ipa:'astʁal',frequency:1,syllableCount:2,pos:'ADJ'}),'lexique_background');
const targets=buildTargetVocabulary([
{word:'chats',lemma:'chat',ipa:'ʃa',frequency:150,syllableCount:1,syllabification:'ʃa',pos:'NOM'},{word:'chat',lemma:'chat',ipa:'ʃa',frequency:120,syllableCount:1,syllabification:'ʃa',pos:'NOM'},{word:'cinéma',lemma:'cinéma',ipa:'sinema',frequency:42.1,syllableCount:3,syllabification:'si.ne.ma',pos:'NOM'},{word:'merci',lemma:'merci',ipa:'mɛʁsi',frequency:1030,syllableCount:2,syllabification:'mɛʁ.si',pos:'ONO'},{word:'maison',lemma:'maison',ipa:'mɛzɔ̃',frequency:80,syllableCount:2,syllabification:'',pos:'NOM'},{word:'bizarre',lemma:'bizarre',ipa:'bizaʁ',frequency:4,syllableCount:2,syllabification:'bi.zaʁ.ə',pos:'ADJ'},{word:'plus',lemma:'plus',ipa:'plys',frequency:100,syllableCount:1,syllabification:'plys',pos:'ADV'},{word:'plus',lemma:'plus',ipa:'ply',frequency:90,syllableCount:1,syllabification:'ply',pos:'ADV'},{word:'astral',lemma:'astral',ipa:'astʁal',frequency:1,syllableCount:2,syllabification:'as.tʁal',pos:'ADJ'},{word:'la',lemma:'le',ipa:'la',frequency:9999,syllableCount:1,syllabification:'la',pos:'ART:def'}]);
assert.equal(targets.filter(i=>i.lemma==='chat').length,1);assert.equal(targets.find(i=>i.lemma==='chat').target,'chat');assert.equal(targets.find(i=>i.target==='cinéma').ageBandCandidate,7);assert.equal(targets.find(i=>i.target==='merci').utilityStatus,'heuristic_product_preselection');assert.equal(targets.find(i=>i.target==='astral').rebuloUtilityTier,'lexique_background');assert.equal(targets.find(i=>i.target==='maison').syllabificationStatus,'needs_source_review');assert.equal(targets.some(i=>i.target==='la'),false);const plus=targets.find(i=>i.target==='plus');assert.equal(plus.targetIpa,'plys');assert.deepEqual(plus.pronunciationVariants.map(i=>i.ipa),['ply']);
const inventory=buildSyllableInventory(targets);assert.equal(inventory.some(i=>i.ipa==='mɛzɔ̃'),false);assert.equal(inventory.some(i=>i.ipa==='bi'),false);const si=inventory.find(i=>i.ipa==='si');assert.equal(si.targetCount,2);assert.equal(si.minAgeBandCandidate,5);
const stats=targetVocabularyStats(targets);assert.equal(stats.total,7);assert.equal(stats.sourceExactSyllabification,5);assert.equal(stats.needsSourceReview,2);assert.equal(stats.alternatePronunciations,1);assert.equal(Object.values(stats.utilityTiers).reduce((a,b)=>a+b,0),stats.total);assert.equal(stats.lexiqueBackgroundTotal,1);assert.equal(stats.rebuloPriorityTotal,6);
console.log('Target vocabulary: age preselection, real non-priority Lexique background, variants and source-only syllables passed.');
