import {buildCreatorCandidate,buildGeneralCreatorCandidate} from './creator-runtime.js';

export const PLAYFUL_PHRASES=Object.freeze([
  'Papa dessine un chat','Le chat regarde papa','Papa tourne près du lit','Le rat file vers le lit','Le chat dort sur le lit','Le rat passe sous le lit','Le chat suit le rat','Le rat regarde le riz','Papa prépare le riz','Le chat renifle le riz','Le rat fait un détour','Papa va au cinéma','Merci papa','Merci pour le dessin','Le rat sous le parapluie','La souris sous le parasol','Un souci sous le soleil','Le chat joue sous la pluie','Papa prend le parapluie','Le rat tourne autour du dé','Le chat cherche la clé','La clé est près du lit','Le dé roule sous le lit','Le rat passe près de la tour','Papa dessine une tour','Le chat regarde la mer','Merci pour le cinéma','Le rat et le chat jouent','Papa cherche la clé du lit','Le chat attend sous le parasol',
  'Le chien regarde la lune','Le lapin court vers la maison','Le cheval passe près du pont','La vache regarde le train','Le singe tient une banane','Le panda mange une pomme','Le lion regarde le château','Le tigre suit le bateau','La tortue passe sous le pont','Le poisson nage près du bateau','Le papillon vole vers la fleur','L abeille tourne autour de la rose','La fourmi passe sous la feuille','L araignée grimpe près de la fenêtre','Le crabe regarde la mer','Le serpent passe près de l arbre','La grenouille saute vers la pluie','Le mouton regarde le nuage','La chèvre monte vers la montagne','Le cochon trouve une carotte',
  'Le train passe sous la lune','Le bateau suit la côte','L avion passe devant le soleil','La voiture roule vers le château','Le vélo passe près de l école','La moto file vers le pont','La fusée monte vers l étoile','Le bus attend près de l école','Le train arrive près de la maison','Le bateau approche de l île','La roue roule près de la porte','Le réveil sonne près du lit','Le téléphone est près du livre','La télévision est dans la maison','La radio joue près du piano','La guitare est près de la chaise','Le tambour est sous la table','La cloche sonne près de l école','Le cadenas ferme la porte','Le marteau est près de la maison',
  'La pomme tombe près du lapin','La poire est près du fromage','L orange roule près du citron','La banane est près du singe','Le raisin est près du fromage','La fraise est sur le gâteau','La cerise tombe près de la glace','La pastèque est près du bateau','La carotte est près du lapin','La tomate est près du pain','La patate est près du fromage','Le pain est près du lait','Le fromage est près du pain','L œuf est près du lait','Le miel est près du gâteau','Le gâteau est près du cadeau','Le bonbon est sous le livre','La glace fond au soleil','La pizza est près de la télévision','Le poisson est près du citron',
  'Le chapeau est près du manteau','La chaussure est sous la chaise','La botte est près de la porte','Le pantalon est sur la chaise','La robe est près du miroir','Les lunettes sont près du livre','La couronne est dans le château','La main tient le crayon','Le pied touche la balle','La bouche goûte le miel','La langue goûte le citron','L œil regarde l étoile','L oreille écoute le piano','La dent croque la pomme','Le cœur est près de la main','Le cerveau imagine une fusée','Le crayon dessine une étoile','Le stylo est près du livre','Les ciseaux sont près du papier','La règle est sous le crayon',
  'Deux chats regardent la lune','Trois lapins courent vers la maison','Quatre poissons nagent près du bateau','Cinq étoiles brillent dans le ciel','Six pommes sont près du panier','Sept fleurs poussent près de l arbre','Huit abeilles tournent autour des fleurs','Neuf ballons sont près de la maison','Dix livres sont près de l école','Un train passe sur le pont','Deux chiens regardent le train','Trois voitures roulent vers le château','Quatre vélos passent près de l école','Cinq oiseaux regardent la mer','Six cadeaux sont près du sapin','Sept bonbons sont près du gâteau','Huit fraises sont près de la glace','Neuf citrons sont près du panier','Dix étoiles entourent la lune','Cent fourmis passent sous la feuille'
]);

const PHRASE_SYMBOLS=Object.freeze({
  zero:{symbol:'0',reading:'zéro',convention:'numeric_symbol'},un:{symbol:'1',reading:'un',convention:'numeric_symbol'},deux:{symbol:'2',reading:'deux',convention:'numeric_symbol'},trois:{symbol:'3',reading:'trois',convention:'numeric_symbol'},quatre:{symbol:'4',reading:'quatre',convention:'numeric_symbol'},cinq:{symbol:'5',reading:'cinq',convention:'numeric_symbol'},six:{symbol:'6',reading:'six',convention:'numeric_symbol'},sept:{symbol:'7',reading:'sept',convention:'numeric_symbol'},huit:{symbol:'8',reading:'huit',convention:'numeric_symbol'},neuf:{symbol:'9',reading:'neuf',convention:'numeric_symbol'},dix:{symbol:'10',reading:'dix',convention:'numeric_symbol'},cent:{symbol:'100',reading:'cent',convention:'numeric_symbol'}
});
export function normalizePhraseWord(value=''){return String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'');}
export function tokenizePhrase(value=''){const text=String(value||'');const tokens=[];const pattern=/[\p{L}\p{N}]+(?:['’\-][\p{L}\p{N}]+)*|[^\p{L}\p{N}]+/gu;for(const match of text.matchAll(pattern)){const token=match[0];const word=/[\p{L}\p{N}]/u.test(token);tokens.push({kind:word?'word':'separator',text:token});}return tokens;}
export function isPhraseInput(value=''){return tokenizePhrase(value).filter(token=>token.kind==='word').length>1;}
function viableCandidate(target,lexicon=[],therapyDefinitions=[]){if(!target||target.assets!=='ready')return null;if(target.mode==='strict')return buildCreatorCandidate(target,lexicon,therapyDefinitions);if(target.mode==='general')return buildGeneralCreatorCandidate(target,lexicon);return null;}
function directPictogram(key,lexicon=[]){const item=(lexicon||[]).find(entry=>entry?.active&&entry?.image&&normalizePhraseWord(entry.label)===key);if(!item)return null;const mode=item.strictEligible===false?'general':'strict';return {answer:item.label,targetIpa:item.ipa,pieces:[{...item,image:item.image,reading:item.label,ipa:item.ipa}],construction:{mode,source:mode==='strict'?'direct_pictogram':'direct_illustration'}};}
export function buildPhrasePlan(value='',targets=[],lexicon=[],therapyDefinitions=[]){
  const tokens=tokenizePhrase(value);const targetMap=new Map();for(const target of targets||[]){const key=normalizePhraseWord(target?.target);if(key&&!targetMap.has(key))targetMap.set(key,target);}
  let wordCount=0;let rebusCount=0;let conventionCount=0;
  const planned=tokens.map(token=>{
    if(token.kind!=='word')return token;wordCount+=1;const key=normalizePhraseWord(token.text);const target=targetMap.get(key)||null;const candidate=viableCandidate(target,lexicon,therapyDefinitions);
    if(candidate){rebusCount+=1;return {kind:'rebus',text:token.text,mode:target.mode,target,candidate};}
    const direct=directPictogram(key,lexicon);if(direct){rebusCount+=1;return {kind:'rebus',text:token.text,mode:direct.construction.mode,target:{target:token.text,source:direct.construction.source},candidate:direct};}
    const symbol=PHRASE_SYMBOLS[key];if(symbol){rebusCount+=1;conventionCount+=1;return {kind:'symbol',text:token.text,...symbol,mode:'general'};}
    return {kind:'text',text:token.text,reason:target?'not_renderable':'not_available'};
  });
  return {input:String(value||''),tokens:planned,wordCount,rebusCount,conventionCount,textCount:Math.max(0,wordCount-rebusCount),complete:wordCount>0&&rebusCount===wordCount};
}
export function playfulPhraseAt(index=0){const size=PLAYFUL_PHRASES.length;if(!size)return '';const safe=((Number(index)||0)%size+size)%size;return PLAYFUL_PHRASES[safe];}
