import {buildAutomaticCreatorTargets,mergeCreatorTargets} from './creator-catalog.js';
import {buildPhrasePlan,isPhraseInput,PLAYFUL_PHRASES} from './phrase-creator.js';
import {buildPhrasePracticeCatalog,recommendedPhrasePractice} from './phrase-practice-catalog.js';
import {buildPronunciationLookup,planPhraseRepresentationPaths} from './rebus-phrase-phonetics.js';
import {buildRepresentationPathIndex} from './rebus-representation-paths.js';
import {loadStaticJSON} from './static-json-cache.js';

const shell=document.querySelector('.app-shell');const form=document.querySelector('#creatorForm');const input=document.querySelector('#target');const surprise=document.querySelector('#phraseSurprise');const feedback=document.querySelector('#creatorFeedback');const result=document.querySelector('#result');const resultLabel=document.querySelector('#resultLabel');const resultWord=document.querySelector('#resultWord');const instruction=document.querySelector('#sheetInstruction');const rebus=document.querySelector('#creatorRebus');const proof=document.querySelector('#phoneticProof');const badge=document.querySelector('.strict-badge');const therapy=document.querySelector('#therapyPanel');const worksheetAnswer=document.querySelector('#worksheetAnswer');const sheetMode=document.querySelector('.sheet-mode');const addButton=document.querySelector('#addToWorksheet');const pdfButton=document.querySelector('#downloadRebus');const alternateButton=document.querySelector('#changeImage');let resources=null;let phraseIndex=0;let practiceCatalog=null;let continuousResources=null;let plannerWorker=null;let plannerSequence=0;const plannerRequests=new Map();let plannerWarmStarted=false;
function normalizeReading(piece){return piece.reading||piece.label||'';}
function pieceNode(piece){const box=document.createElement('div');box.className='piece';if(piece.operationType==='grapheme'){box.classList.add('grapheme-piece');const symbol=document.createElement('strong');symbol.className='grapheme-symbol';symbol.textContent=piece.grapheme||piece.label||'';const label=document.createElement('span');label.textContent=normalizeReading(piece);box.append(symbol,label);return box;}if(piece.operationType==='spatial_relation'){box.classList.add('spatial-piece');const diagram=document.createElement('div');diagram.className='spatial-diagram';diagram.setAttribute('aria-hidden','true');const reference=document.createElement('span');reference.className='spatial-reference';reference.textContent='■';const subject=document.createElement('span');subject.className='spatial-subject';subject.textContent='●';diagram.append(reference,subject);const label=document.createElement('span');label.textContent=normalizeReading(piece);box.append(diagram,label);return box;}const img=document.createElement('img');img.src=piece.image;img.alt=normalizeReading(piece);img.decoding='async';const label=document.createElement('span');label.textContent=normalizeReading(piece);box.append(img,label);return box;}
async function loadJSON(path,{cache='no-store'}={}){return loadStaticJSON(path,{cache});}
async function loadResources(){if(resources)return resources;const [lexicon,corpus,therapyTargets,coverage]=await Promise.all([loadJSON('data/lexicon-seed.json'),loadJSON('data/corpus-pilot.json'),loadJSON('data/therapy-targets.json'),loadJSON('data/coverage-report.json')]);resources={lexicon,therapy:therapyTargets.targets||[],targets:mergeCreatorTargets(corpus.items||[],buildAutomaticCreatorTargets(coverage))};return resources;}
async function loadContinuousResources(){if(continuousResources)return continuousResources;const [pronunciations,compactRuntime]=await Promise.all([loadJSON('data/rebus-pronunciation-lexicon.json',{cache:'force-cache'}),loadJSON('data/rebulo-compact-runtime.json',{cache:'force-cache'})]);const bankRows=Array.isArray(compactRuntime?.bankRows)?compactRuntime.bankRows:[];if(!bankRows.length)throw new Error('Compact runtime bank is empty');continuousResources={pronunciationLookup:buildPronunciationLookup(pronunciations),bankRows,optionIndex:buildRepresentationPathIndex(bankRows)};return continuousResources;}
function workerInstance(){if(plannerWorker)return plannerWorker;if(typeof Worker!=='function')return null;try{plannerWorker=new Worker(new URL('./phrase-planner-worker.js',import.meta.url),{type:'module',name:'rebulo-phrase-planner'});plannerWorker.addEventListener('message',event=>{const message=event.data||{};const pending=plannerRequests.get(message.id);if(!pending)return;plannerRequests.delete(message.id);if(message.type==='error')pending.reject(new Error(message.message||'Phrase worker error'));else pending.resolve(message);});plannerWorker.addEventListener('error',event=>{for(const pending of plannerRequests.values())pending.reject(event.error||new Error(event.message||'Phrase worker error'));plannerRequests.clear();plannerWorker?.terminate();plannerWorker=null;plannerWarmStarted=false;});return plannerWorker;}catch{return null;}}
function askWorker(type,value=''){const worker=workerInstance();if(!worker)return null;const id=++plannerSequence;return new Promise((resolve,reject)=>{plannerRequests.set(id,{resolve,reject});worker.postMessage({type,id,value});});}
function warmContinuousPlanner(){if(plannerWarmStarted)return;plannerWarmStarted=true;const request=askWorker('warm');if(!request){plannerWarmStarted=false;return;}request.then(message=>{if(shell){shell.dataset.phrasePlanner='worker';shell.dataset.phrasePlannerPrepareMs=String(Math.round(message.prepareMs||0));}}).catch(()=>{plannerWarmStarted=false;});}
async function planContinuous(value){const request=askWorker('plan',value);if(request){const message=await request;if(shell){shell.dataset.phrasePlanner='worker';shell.dataset.phrasePlannerPrepareMs=String(Math.round(message.prepareMs||0));shell.dataset.phrasePlannerLastMs=String(Number(message.planMs||0).toFixed(1));}return message.planned;}const continuous=await loadContinuousResources();if(shell)shell.dataset.phrasePlanner='main-thread-fallback';return planPhraseRepresentationPaths(value,continuous.pronunciationLookup,continuous.bankRows,{mode:'general',limit:6,maxPieces:16,allowGaps:true,optionIndex:continuous.optionIndex});}
async function loadPracticeCatalog(){if(practiceCatalog)return practiceCatalog;const data=await loadResources();practiceCatalog=buildPhrasePracticeCatalog(PLAYFUL_PHRASES,data.targets,data.lexicon,data.therapy);return practiceCatalog;}
function symbolNode(token){const box=document.createElement('span');box.className='piece phrase-symbol-piece';box.setAttribute('role','img');box.setAttribute('aria-label',`${token.symbol}, se lit ${token.reading}`);const symbol=document.createElement('strong');symbol.className='phrase-number-symbol';symbol.textContent=token.symbol;box.appendChild(symbol);return box;}
function percent(value){return `${Math.round((Number(value)||0)*100)} %`;}
function finishPhraseChrome(){if(therapy)therapy.hidden=true;if(worksheetAnswer)worksheetAnswer.hidden=true;if(sheetMode)sheetMode.hidden=true;if(addButton)addButton.hidden=true;if(pdfButton)pdfButton.hidden=true;if(alternateButton)alternateButton.hidden=true;}
function addPhraseLegend(hasMissing=false){const legend=document.createElement('div');legend.className='phrase-coverage-legend';const represented=document.createElement('span');represented.className='phrase-legend-rebus';represented.textContent='Pièces du rébus';legend.appendChild(represented);if(hasMissing){const missing=document.createElement('span');missing.className='phrase-legend-missing';missing.textContent='Texte / sons non représentés';legend.appendChild(missing);}rebus.appendChild(legend);}
function setSimpleProof(complete,details=''){proof.textContent=complete?'Rébus complet.':'Rébus partiel.';proof.title=details;proof.dataset.debugDetails=details;}
function uncoveredTextNode(value='',tagText='texte'){const text=document.createElement('span');text.className='phrase-text-token phrase-uncovered-token';text.setAttribute('aria-label',`Texte non représenté : ${value}`);const tag=document.createElement('small');tag.textContent=tagText;const content=document.createElement('strong');content.textContent=value;text.append(tag,content);return text;}
function renderPhrase(plan){result.hidden=false;result.dataset.sheetMode='phrase';if(badge){badge.textContent=plan.complete?'Rébus complet':'Rébus partiel';badge.title=plan.complete?'Toute la phrase est représentée':'Une partie reste en texte';badge.classList.add('general-badge');}resultLabel.textContent='Phrase';resultWord.textContent=plan.input;instruction.textContent=plan.complete?'Toute la phrase est transformée en rébus.':'Les pièces du rébus sont séparées du texte qui reste à représenter.';rebus.replaceChildren();rebus.className='rebus-row phrase-flow';addPhraseLegend(plan.textCount>0);for(const token of plan.tokens){if(token.kind==='separator'){const sep=document.createElement('span');sep.className='phrase-separator';sep.textContent=token.text;rebus.appendChild(sep);continue;}if(token.kind==='text'){rebus.appendChild(uncoveredTextNode(token.text));continue;}const group=document.createElement('span');group.className='phrase-rebus-token';group.setAttribute('aria-label',`Rébus pour ${token.text}`);if(token.kind==='symbol'){group.appendChild(symbolNode(token));}else{token.candidate.pieces.forEach(piece=>group.appendChild(pieceNode(piece)));}rebus.appendChild(group);}const practice=plan.practice||{};const details=`${plan.rebusCount}/${plan.wordCount} mots en rébus · couverture visuelle ${percent(practice.rebusRatio)} · strict ${percent(practice.strictRebusRatio)}${plan.conventionCount?` · ${plan.conventionCount} convention(s)`:''}`;setSimpleProof(plan.complete,details);feedback.textContent=plan.complete?'La phrase est entièrement représentée.':plan.rebusCount?'Phrase partielle : ce qui manque reste clairement en texte.':'Aucun rébus disponible pour cette phrase.';finishPhraseChrome();}
function operationNode(operation){if(operation.kind==='unresolved_word')return uncoveredTextNode(operation.text||operation.label||'mot','prononciation inconnue');if(operation.kind==='gap'){const gap=document.createElement('span');gap.className='phrase-sound-gap phrase-uncovered-token';const words=[...new Set((operation.sourceWords||[]).map(word=>word.text))];const tag=document.createElement('small');tag.textContent='sons non représentés';const content=document.createElement('strong');content.textContent=words.length?words.join(' / '):(operation.targetIpa||'partie sonore');gap.append(tag,content);gap.title=`Sons non couverts : /${operation.targetIpa||''}/`;return gap;}const node=operation.kind==='image'?pieceNode({image:operation.image,reading:operation.label,label:operation.label}):symbolNode({symbol:operation.symbol||operation.label,reading:operation.label});if(operation.crossesWordBoundary){node.classList.add('phrase-cross-boundary');node.title=`Cette pièce traverse ${operation.sourceWords.map(word=>word.text).join(' + ')}`;}return node;}
function renderContinuousPhrase(value,planned){const route=planned.routes?.[0];if(!route||!route.operations?.length)return false;result.hidden=false;result.dataset.sheetMode='phrase';resultLabel.textContent='Phrase';resultWord.textContent=value;if(badge){badge.textContent=route.complete?'Rébus complet':'Rébus partiel';badge.title='Planification phonétique continue ; les lacunes restent explicites';badge.classList.add('general-badge');}instruction.textContent=route.complete?'Toute la suite sonore est couverte.':'Les sons non couverts restent signalés ; les pièces trouvées restent visibles.';rebus.replaceChildren();rebus.className='rebus-row phrase-flow phrase-continuous-flow';const unresolvedCount=Number(route.unresolvedWordCount)||0;route.operations.forEach(operation=>rebus.appendChild(operationNode(operation)));rebus.scrollLeft=0;const ratio=route.scoreBreakdown?.coverageRatio||0;const representedCount=route.operations.filter(operation=>!['gap','unresolved_word'].includes(operation.kind)).length;const details=`Couverture phonétique connue ${percent(ratio)} · ${representedCount} représentation(s) · ${route.crossWordOperationCount||0} traversée(s) entre mots · ${route.uncoveredUnits||0} unité(s) phonétique(s) non couverte(s)${unresolvedCount?` · ${unresolvedCount} mot(s) sans prononciation disponible`:''}`;setSimpleProof(route.complete,details);feedback.textContent=route.complete?'La phrase est entièrement représentée.':representedCount?`Rébus partiel : ${representedCount} pièce${representedCount>1?'s':''} trouvée${representedCount>1?'s':''}, les sons manquants restent indiqués.`:'Aucune pièce de rébus disponible pour les sons reconnus.';finishPhraseChrome();return true;}
async function createPhrase(value){const started=performance.now();try{if(feedback)feedback.textContent='Préparation des sons…';const planned=await planContinuous(value);if(renderContinuousPhrase(value,planned)){if(shell)shell.dataset.phraseVisibleMs=String(Math.round(performance.now()-started));return;}}catch(error){console.info('Planification phonétique continue indisponible, utilisation du secours mot par mot.',error);}try{const data=await loadResources();renderPhrase(buildPhrasePlan(value,data.targets,data.lexicon,data.therapy));}catch(error){console.error(error);result.hidden=true;feedback.textContent='Chargement impossible pour la phrase.';}}
form?.addEventListener('submit',event=>{const value=input?.value||'';const phraseSelected=shell?.dataset.creatorKind==='phrase';if(!phraseSelected&&!isPhraseInput(value))return;event.preventDefault();event.stopImmediatePropagation();createPhrase(value.trim());},true);
document.querySelectorAll('[data-creator-kind="phrase"]').forEach(button=>button.addEventListener('click',warmContinuousPlanner));
surprise?.addEventListener('click',async()=>{if(!input)return;warmContinuousPlanner();try{const catalog=await loadPracticeCatalog();const recommended=recommendedPhrasePractice(catalog,phraseIndex++);if(!recommended){feedback.textContent='Aucune phrase assez visuelle avec les briques disponibles.';return;}input.value=recommended.phrase;await createPhrase(recommended.phrase);}catch(error){console.error(error);feedback.textContent='Chargement impossible pour les phrases.';}});
if(shell?.dataset.creatorKind==='phrase')warmContinuousPlanner();
