import {buildAutomaticCreatorTargets,mergeCreatorTargets} from './creator-catalog.js';
import {buildPhrasePlan,isPhraseInput,PLAYFUL_PHRASES} from './phrase-creator.js';
import {buildPhrasePracticeCatalog,recommendedPhrasePractice} from './phrase-practice-catalog.js';
import {playableRepresentationBankRows} from './generated-play-catalog.js';
import {planPhraseRepresentationPaths} from './rebus-phrase-phonetics.js';

const form=document.querySelector('#creatorForm');const input=document.querySelector('#target');const surprise=document.querySelector('#phraseSurprise');const feedback=document.querySelector('#creatorFeedback');const result=document.querySelector('#result');const resultLabel=document.querySelector('#resultLabel');const resultWord=document.querySelector('#resultWord');const instruction=document.querySelector('#sheetInstruction');const rebus=document.querySelector('#creatorRebus');const proof=document.querySelector('#phoneticProof');const badge=document.querySelector('.strict-badge');const therapy=document.querySelector('#therapyPanel');const worksheetAnswer=document.querySelector('#worksheetAnswer');const sheetMode=document.querySelector('.sheet-mode');const addButton=document.querySelector('#addToWorksheet');const pdfButton=document.querySelector('#downloadRebus');const alternateButton=document.querySelector('#changeImage');let resources=null;let phraseIndex=0;let practiceCatalog=null;let continuousResources=null;
function normalizeReading(piece){return piece.reading||piece.label||'';}
function pieceNode(piece){const box=document.createElement('div');box.className='piece';if(piece.operationType==='grapheme'){box.classList.add('grapheme-piece');const symbol=document.createElement('strong');symbol.className='grapheme-symbol';symbol.textContent=piece.grapheme||piece.label||'';const label=document.createElement('span');label.textContent=normalizeReading(piece);box.append(symbol,label);return box;}if(piece.operationType==='spatial_relation'){box.classList.add('spatial-piece');const diagram=document.createElement('div');diagram.className='spatial-diagram';diagram.setAttribute('aria-hidden','true');const reference=document.createElement('span');reference.className='spatial-reference';reference.textContent='■';const subject=document.createElement('span');subject.className='spatial-subject';subject.textContent='●';diagram.append(reference,subject);const label=document.createElement('span');label.textContent=normalizeReading(piece);box.append(diagram,label);return box;}const img=document.createElement('img');img.src=piece.image;img.alt=normalizeReading(piece);const label=document.createElement('span');label.textContent=normalizeReading(piece);box.append(img,label);return box;}
async function loadJSON(path,{cache='no-store'}={}){const response=await fetch(path,{cache});if(!response.ok)throw new Error(path);return response.json();}
async function loadResources(){if(resources)return resources;const [lexicon,corpus,therapyTargets,coverage]=await Promise.all([loadJSON('data/lexicon-seed.json'),loadJSON('data/corpus-pilot.json'),loadJSON('data/therapy-targets.json'),loadJSON('data/coverage-report.json')]);resources={lexicon,therapy:therapyTargets.targets||[],targets:mergeCreatorTargets(corpus.items||[],buildAutomaticCreatorTargets(coverage))};return resources;}
async function loadContinuousResources(){if(continuousResources)return continuousResources;const [pronunciations,soundCatalog,visibleConventions]=await Promise.all([loadJSON('data/rebus-pronunciation-lexicon.json',{cache:'force-cache'}),loadJSON('data/rebus-sound-catalog.json',{cache:'force-cache'}),loadJSON('data/rebus-visible-conventions.json',{cache:'force-cache'})]);continuousResources={pronunciations,bankRows:playableRepresentationBankRows(soundCatalog,visibleConventions)};return continuousResources;}
async function loadPracticeCatalog(){if(practiceCatalog)return practiceCatalog;const data=await loadResources();practiceCatalog=buildPhrasePracticeCatalog(PLAYFUL_PHRASES,data.targets,data.lexicon,data.therapy);return practiceCatalog;}
function symbolNode(token){const box=document.createElement('span');box.className='piece phrase-symbol-piece';box.setAttribute('role','img');box.setAttribute('aria-label',`${token.symbol}, se lit ${token.reading}`);const symbol=document.createElement('strong');symbol.className='phrase-number-symbol';symbol.textContent=token.symbol;box.appendChild(symbol);return box;}
function percent(value){return `${Math.round((Number(value)||0)*100)} %`;}
function finishPhraseChrome(){if(therapy)therapy.hidden=true;if(worksheetAnswer)worksheetAnswer.hidden=true;if(sheetMode)sheetMode.hidden=true;if(addButton)addButton.hidden=true;if(pdfButton)pdfButton.hidden=true;if(alternateButton)alternateButton.hidden=true;}
function renderPhrase(plan){result.hidden=false;result.dataset.sheetMode='phrase';if(badge){badge.textContent=plan.conventionCount?'Rébus':'Phrase';badge.title=plan.conventionCount?'Phrase avec conventions de rébus explicites':'Phrase composée de pictogrammes disponibles';badge.classList.add('general-badge');}resultLabel.textContent='Phrase';resultWord.textContent=plan.input;instruction.textContent=plan.complete?'Toute la phrase est transformée en rébus.':'Les mots sans rébus disponible restent en texte.';rebus.replaceChildren();rebus.classList.add('phrase-flow');for(const token of plan.tokens){if(token.kind==='separator'){const sep=document.createElement('span');sep.className='phrase-separator';sep.textContent=token.text;rebus.appendChild(sep);continue;}if(token.kind==='text'){const text=document.createElement('span');text.className='phrase-text-token';text.textContent=token.text;rebus.appendChild(text);continue;}const group=document.createElement('span');group.className='phrase-rebus-token';group.setAttribute('aria-label',`Rébus pour ${token.text}`);if(token.kind==='symbol'){group.appendChild(symbolNode(token));}else{token.candidate.pieces.forEach(piece=>group.appendChild(pieceNode(piece)));}rebus.appendChild(group);}const practice=plan.practice||{};proof.textContent=`${plan.rebusCount} mot${plan.rebusCount>1?'s':''} en rébus · ${plan.textCount} mot${plan.textCount>1?'s':''} en texte · couverture visuelle ${percent(practice.rebusRatio)} · strict ${percent(practice.strictRebusRatio)}${plan.conventionCount?` · ${plan.conventionCount} convention${plan.conventionCount>1?'s':''}`:''}`;feedback.textContent=plan.rebusCount?`Phrase créée : ${plan.rebusCount} mot${plan.rebusCount>1?'s':''} transformé${plan.rebusCount>1?'s':''} sur ${plan.wordCount}.`:'Aucun rébus disponible pour cette phrase.';finishPhraseChrome();}
function operationNode(operation){if(operation.kind==='gap'){const gap=document.createElement('span');gap.className='phrase-sound-gap';const words=[...new Set((operation.sourceWords||[]).map(word=>word.text))];gap.textContent=words.length?words.join(' / '):'son non couvert';gap.title='Cette partie sonore reste non couverte par la banque exacte.';return gap;}const node=operation.kind==='image'?pieceNode({image:operation.image,reading:operation.label,label:operation.label}):symbolNode({symbol:operation.symbol||operation.label,reading:operation.label});if(operation.crossesWordBoundary){node.classList.add('phrase-cross-boundary');node.title=`Cette pièce traverse ${operation.sourceWords.map(word=>word.text).join(' + ')}`;}return node;}
function renderContinuousPhrase(value,planned){const route=planned.routes?.[0];if(!route||!route.operations?.length||route.coverageUnits<=0)return false;result.hidden=false;result.dataset.sheetMode='phrase';resultLabel.textContent='Phrase · sons continus';resultWord.textContent=value;if(badge){badge.textContent=route.complete?'Rébus continu':'Rébus partiel';badge.title='Planification phonétique continue, sans approximation cachée';badge.classList.add('general-badge');}instruction.textContent=route.complete?'Toute la suite sonore de la phrase est couverte. Les pièces peuvent traverser la frontière entre deux mots.':'Rebulo montre ce que la banque exacte couvre et laisse explicitement le reste non couvert.';rebus.replaceChildren();rebus.classList.add('phrase-flow','phrase-continuous-flow');route.operations.forEach(operation=>rebus.appendChild(operationNode(operation)));const ratio=route.scoreBreakdown?.coverageRatio||0;proof.textContent=`Couverture sonore ${percent(ratio)} · ${route.operations.filter(operation=>operation.kind!=='gap').length} représentation(s) · ${route.crossWordOperationCount||0} traversée(s) entre mots · ${route.uncoveredUnits||0} unité(s) sonore(s) non couverte(s).`;feedback.textContent=route.complete?'Phrase planifiée sur sa chaîne sonore complète.':`Couverture partielle honnête : ${percent(ratio)} des sons sont représentés.`;finishPhraseChrome();return true;}
async function createPhrase(value){try{const data=await loadResources();const wordPlan=buildPhrasePlan(value,data.targets,data.lexicon,data.therapy);renderPhrase(wordPlan);try{const continuous=await loadContinuousResources();const planned=planPhraseRepresentationPaths(value,continuous.pronunciations,continuous.bankRows,{mode:'general',limit:6,maxPieces:16,allowGaps:true});if(planned.status==='routes_found')renderContinuousPhrase(value,planned);}catch(error){console.info('Planification continue indisponible, conservation du plan mot par mot.',error);}}catch(error){console.error(error);result.hidden=true;feedback.textContent='Chargement impossible pour la phrase.';}}
form?.addEventListener('submit',event=>{if(!isPhraseInput(input?.value||''))return;event.preventDefault();event.stopImmediatePropagation();createPhrase(input.value.trim());},true);
surprise?.addEventListener('click',async()=>{if(!input)return;try{const catalog=await loadPracticeCatalog();const recommended=recommendedPhrasePractice(catalog,phraseIndex++);if(!recommended){feedback.textContent='Aucune phrase assez visuelle avec les briques disponibles.';return;}input.value=recommended.phrase;await createPhrase(recommended.phrase);}catch(error){console.error(error);feedback.textContent='Chargement impossible pour les phrases.';}});
